import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Book } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
// Color Palette (Berry Twilight)
const colors = {
  mainBackground: '#2C2A3B',
  secondaryBackground: '#3A374F',
  primaryText: '#F8F5FB',
  secondaryText: '#C7C3D4',
  accentPrimary: '#D9456F', // Berry Pink
  accentAlternative: '#B5375A', // Deeper Red
  success: '#6BBF59',
  error: '#D9534F',
};

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Resource Sharing Hub",
  description: "Generated by create next app",
};
  const currentYear = new Date().getFullYear();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="py-6 bg-primary">
      <nav className="flex md:justify-between md:items-center px-4 mx-auto max-w-7xl">
        <Link href='/' className="font-bold text-2xl primary-text primary-text-hover duration-500 ">Resource Hub</Link>

        <ul className="hidden md:flex gap-8 items-center justify-center">
          {/* <li className="">
            <button  className="p-3 hover:bg-[#334155] hover:rounded-full primary-text md:text-lg lg:text-xl font-semibold cursor-pointer primary-text-hover duration-500">Features</button>
          </li> */}
          <li className="">
            <Link href='/about'  className="p-3 hover:bg-[#334155] hover:rounded-full primary-text md:text-lg lg:text-xl font-semibold cursor-pointer primary-text-hover duration-500">About</Link>
          </li>
          <li className="">
            <Link href='/upload-resources' className="p-3 hover:bg-[#334155] hover:rounded-full primary-text md:text-lg lg:text-xl font-semibold cursor-pointer primary-text-hover duration-500">Resources</Link>
          </li>
          {/* <li className="">
            <button  className="primary-text p-3 hover:bg-[#334155] hover:rounded-full md:text-lg lg:text-xl font-semibold cursor-pointer primary-text-hover duration-500">Contact</button>
          </li> */}
        </ul>
      </nav>

    </header>
        {children}

        <footer className={`bg-gray-900 primary-text py-10 px-4`}>
      <div className="container mx-auto flex flex-col items-center text-center space-y-8">
        {/* Logo and Tagline */}
        <div className="flex flex-col items-center space-y-2">
          <a href="/" className="flex items-center space-x-2">
            <Book className={`text-[${colors.accentPrimary}]`} size={28} />
            <span className="text-2xl font-bold tracking-tight text-[${colors.primaryText}]">StudyHub</span>
          </a>
          <p className="text-sm max-w-md">
            Connecting students with shared knowledge to help you succeed.
          </p>
        </div>

        {/* Navigation Links */}
        <div className="flex flex-wrap justify-center gap-x-6 gap-y-2 text-sm font-medium">
          <a href="/browse" className={`hover:text-[${colors.accentPrimary}] transition-colors duration-200`}>Browse Resources</a>
          <a href="/upload" className={`hover:text-[${colors.accentPrimary}] transition-colors duration-200`}>Upload Work</a>
          <a href="/about" className={`hover:text-[${colors.accentPrimary}] transition-colors duration-200`}>About Us</a>
          <a href="/contact" className={`hover:text-[${colors.accentPrimary}] transition-colors duration-200`}>Contact</a>
          <a href="/privacy" className={`hover:text-[${colors.accentPrimary}] transition-colors duration-200`}>Privacy Policy</a>
          <a href="/terms" className={`hover:text-[${colors.accentPrimary}] transition-colors duration-200`}>Terms of Service</a>
        </div>

        {/* Copyright */}
        <div className={`pt-6 border-t border-[${colors.secondaryBackground}] w-full max-w-xl`}>
          <p className="text-xs">
            &copy; {currentYear} StudyHub. All rights reserved.
          </p>
        </div>
      </div>
    </footer>
      </body>
    </html>
  );
}
