"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Book } from "lucide-react";
import { useUserStore } from "@/store/store";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const currentYear = new Date().getFullYear();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { isLoggedIn } = useUserStore(state => state);
  
  return (
    <html lang="en">
      <head>
        <title>Resource Sharing Hub</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          "--main-bg": "#2C2A3B",
          "--secondary-bg": "#3A374F",
          "--primary-text": "#F8F5FB",
          "--secondary-text": "#C7C3D4",
          "--accent-primary": "#D9456F",
          "--accent-alternative": "#B5375A",
        } as React.CSSProperties}
      >
        <header className="py-6 bg-[var(--main-bg)]">
          <nav className="flex md:justify-between md:items-center px-4 mx-auto max-w-7xl">
            <Link href='/' className="font-bold text-2xl text-[var(--primary-text)] hover:text-[var(--accent-primary)] duration-500">
              Resource Hub
            </Link>

            <ul className="hidden md:flex gap-8 items-center justify-center">
              <li>
                <Link href='/about' className="p-3 hover:bg-[#334155] hover:rounded-full text-[var(--primary-text)] md:text-lg lg:text-xl font-semibold cursor-pointer hover:text-[var(--accent-primary)] duration-500">
                  About
                </Link>
              </li>
              <li>
                <Link href='/resources' className="p-3 hover:bg-[#334155] hover:rounded-full text-[var(--primary-text)] md:text-lg lg:text-xl font-semibold cursor-pointer hover:text-[var(--accent-primary)] duration-500">
                  Resources
                </Link>
              </li>
              <li>
                <Link href='/upload-resources' className="p-3 hover:bg-[#334155] hover:rounded-full text-[var(--primary-text)] md:text-lg lg:text-xl font-semibold cursor-pointer hover:text-[var(--accent-primary)] duration-500">
                  Upload Document
                </Link>
              </li>
              <li>
                {!isLoggedIn ? (
                  <Link href='/login' className="text-[var(--primary-text)] p-3 hover:bg-[#334155] hover:rounded-full md:text-lg lg:text-xl font-semibold cursor-pointer hover:text-[var(--accent-primary)] duration-500">
                    Login
                  </Link>
                ) : (
                  <Link href='/profile' className="text-[var(--primary-text)] p-3 hover:bg-[#334155] hover:rounded-full md:text-lg lg:text-xl font-semibold cursor-pointer hover:text-[var(--accent-primary)] duration-500">
                    Profile
                  </Link>
                )}
              </li>
            </ul>
          </nav>
        </header>
        
        {children}

        <footer className="bg-gray-900 text-[var(--primary-text)] py-10 px-4">
          <div className="container mx-auto flex flex-col items-center text-center space-y-8">
            <div className="flex flex-col items-center space-y-2">
              <a href="/" className="flex items-center space-x-2">
                <Book className="text-[var(--accent-primary)]" size={28} />
                <span className="text-2xl font-bold tracking-tight">StudyHub</span>
              </a>
              <p className="text-sm max-w-md">
                Connecting students with shared knowledge to help you succeed.
              </p>
            </div>

            <div className="flex flex-wrap justify-center gap-x-6 gap-y-2 text-sm font-medium">
              {["Browse Resources", "Upload Work", "About Us", "Contact", "Privacy Policy", "Terms of Service"].map((item, index) => (
                <a 
                  key={index} 
                  href={`/${item.toLowerCase().replace(/\s+/g, '-')}`}
                  className="hover:text-[var(--accent-primary)] transition-colors duration-200"
                >
                  {item}
                </a>
              ))}
            </div>

            <div className="pt-6 border-t border-[var(--secondary-bg)] w-full max-w-xl">
              <p className="text-xs">
                &copy; {currentYear} StudyHub. All rights reserved.
              </p>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}